### PR TITLE
Warn about OOM

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't think this is the place to document a general JSON.stringify limitation. Also, using that package changes the output type and it's not clear to the user how to also read a newline-separated JSON. And the package has not been touched in years.

**Comment by dandv** [comment]
I just saw that [exit-hook](https://www.npmjs.com/package/exit-hook), another one of your useful packages, advised to use a different package for something it didn't support, so I thought it would be OK to do something similar in this case.

**Comment by sindresorhus** [comment]
Hmm, I'm ok with documenting this, but you need to find a better maintained package for this, better document how newline-separated JSON differs, and move it to a top-level `Tips` section.

**Comment by sindresorhus** [comment]
Bump

**Pull request closed without merging**
